"""venue_hours_facility_status_pricing

Revision ID: 430b61085678
Revises: 6c6fe6a485d7
Create Date: 2026-09-15 15:23:50.601065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '430b61085678'
down_revision: Union[str, None] = '6c6fe6a485d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operating_hours_id'), table_name='operating_hours')
    op.drop_index(op.f('ix_operating_hours_venue_id'), table_name='operating_hours')
    op.drop_table('operating_hours')
    facility_status_enum = postgresql.ENUM('ACTIVE', 'MAINTENANCE', 'INACTIVE', name='facilitystatus')
    facility_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('courts', sa.Column('status', facility_status_enum, server_default='ACTIVE', nullable=False))
    op.add_column('courts', sa.Column('status_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_courts_status'), 'courts', ['status'], unique=False)
    op.add_column('venues', sa.Column('status', facility_status_enum, server_default='ACTIVE', nullable=False))
    op.add_column('venues', sa.Column('status_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('venues', sa.Column('opening_time', sa.Time(), server_default='08:00:00', nullable=False))
    op.add_column('venues', sa.Column('closing_time', sa.Time(), server_default='00:00:00', nullable=False))
    op.create_index(op.f('ix_venues_status'), 'venues', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_status'), table_name='venues')
    op.drop_column('venues', 'closing_time')
    op.drop_column('venues', 'opening_time')
    op.drop_column('venues', 'status_note')
    op.drop_column('venues', 'status')
    op.drop_index(op.f('ix_courts_status'), table_name='courts')
    op.drop_column('courts', 'status_note')
    op.drop_column('courts', 'status')
    op.create_table('operating_hours',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opening_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('closing_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('operating_hours_venue_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('operating_hours_pkey')),
    sa.UniqueConstraint('venue_id', 'day_of_week', name=op.f('uq_venue_operating_day'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_operating_hours_venue_id'), 'operating_hours', ['venue_id'], unique=False)
    op.create_index(op.f('ix_operating_hours_id'), 'operating_hours', ['id'], unique=False)
    # ### end Alembic commands ###
