"""bd_friendly_venue_location_fields

Revision ID: 6c6fe6a485d7
Revises: 9305d91b3d78
Create Date: 2026-09-15 13:46:44.475137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c6fe6a485d7'
down_revision: Union[str, None] = '9305d91b3d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('venues', sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), server_default='Chattogram', nullable=False))
    op.add_column('venues', sa.Column('google_maps_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.create_index(op.f('ix_venues_area'), 'venues', ['area'], unique=False)
    op.create_index(op.f('ix_venues_district'), 'venues', ['district'], unique=False)
    op.drop_column('venues', 'state_province')
    op.drop_column('venues', 'city')
    op.drop_column('venues', 'postal_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('venues', sa.Column('state_province', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_venues_district'), table_name='venues')
    op.drop_index(op.f('ix_venues_area'), table_name='venues')
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.drop_column('venues', 'google_maps_url')
    op.drop_column('venues', 'district')
    op.drop_column('venues', 'area')
    # ### end Alembic commands ###
